# Generated by Django 3.0.2 on 2020-01-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('body', models.TextField(default='')),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=5)),
                ('day', models.CharField(max_length=5)),
                ('reason', models.TextField(default='')),
            ],
        ),
    ]
