# Generated by Django 3.0.2 on 2020-01-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0003_post_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.TextField(default=''),
        ),
    ]
